// Import necessary types and components from Next.js and other libraries
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

// Initialize the Inter font with the Latin subset
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the application, such as title and description
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout component for the entire application.
 * It sets up the basic HTML structure, including the font and notification toaster.
 * @param {object} props - The properties for the component.
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout.
 * @returns {JSX.Element} The root layout of the application.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Render the child components passed to the layout */}
        {children}
        {/* Render the Toaster component to enable toast notifications throughout the app */}
        <Toaster />
      </body>
    </html>
  );
}